---
- name: Ensure /opt/devops directory exists
  hosts: all
  become: yes
  tasks:
    - name: Create /opt/devops directory
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

- name: Ensure /opt/devops/info.txt exists
  hosts: all
  become: yes
  tasks:
    - name: Create info.txt with content
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible!"
        mode: '0644'       
