---
- name: Ensure /opt/devops directory exists
  hosts: all
  become: yes
  tasks:
    - name: Create /opt/devops directory
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

- name: Ensure /opt/devops/info.txt exists
  hosts: all
  become: yes
  tasks:
    - name: Create info.txt with content
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible!"
        mode: '0644'       

  name:Repeat: Ensure /opt/devops has necessary files
  hosts: all
  become: yes
  tasks:
    - name: Create a README file in /opt/devops
      copy:
        dest: /opt/devops/README.txt
        content: "This is a managed directory by Ansible."
        mode: '0644'

  name: Set permissions for /opt/devops
  file:
        path: /opt/devops
        mode: '0755'
        state: directory  

  name:Final Check: Ensure system setup is correct
  hosts: all
  become: yes
  tasks:
    - name: Display the contents of /opt/devops
      command: cat /opt/devops/info.txt
      register: file_contents        

      name: Print the contents of info.txt
      debug:
        msg: "{{ file_contents.stdout }}"
...        