---
- name: Install HTTP server 
  hosts: n1
  become: yes
  tasks:
    - name: Install Apache2 
      apt:
        name: Apache2
        state: present

    - name: Start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes

...        