---
- name: Install HTTP server
  hosts: n1
  become: yes
  tasks:
    - name: Install Apache (Ubuntu/Debian)
      apt:
        name: apache2  
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

...        