---
- name: Install and start HTTPD
  hosts: web_servers
  become: yes
  tasks:
    - name: Install Apache (httpd) on RedHat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" or ansible_os_family == "centos"

    - name: Start and enable httpd service (RedHat)
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat" or ansible_os_family == "centos"

    - name: Install Apache (apache2) on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "centos"

    - name: Start and enable apache2 service (Ubuntu)
      systemd:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "centos"

...        