---
- name: Install and start HTTPD
  hosts: web_servers
  become: yes
  tasks:
    - name: Install Apache (httpd)
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: Start and enable httpd service (RedHat)
  systemd:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"


- name: Install Apache (Ubuntu/Debian)
  apt:
        name: apache2  
        state: present
        update_cache: yes
  when: ansible _distribution == "ubuntu"

...        