---
- name: variables Demo
  hosts: web_servers
  become: yes
  vars:
  myusername: AdedamolaF

  tasks:
    - name: update Dynamic page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
... 